# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

rec {
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  # we have 4 cores
  # limit nix-build to 3 cores to avoid hanging the system
  # (actually, the system did hang because out-of-memory
  # which is solved by adding swap)
  nix.settings.cores = 3;
  nix.settings.max-jobs = 1;

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/d8575da4-83d8-43f2-ae94-cfb8e277cad3";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/4804-675E";
      fsType = "vfat";
    };

  # https://nixos.wiki/wiki/Swap
  swapDevices = [
    {
      # dd if=/dev/zero of=/var/swapfile bs=1M count=16k status=progress
      # mkswap /var/swapfile
      device = "/var/swapfile";
      size = 16 * 1024; # size in MiB -> 16 GiB
      # better security
      # but this breaks hibernation
      # fixme: setting this from true to false causes rebuild to fail:
      # swapon: /var/swapfile: read swap header failed
      #randomEncryption.enable = true;
    }
  ];

  # slow boot: waiting for device
  #boot.resumeDevice = "/var/swapfile";
  boot.resumeDevice = fileSystems."/".device;
  boot.kernelParams = [
    #"systemd.unified_cgroup_hierarchy=0" # ?
    # https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate
    # filefrag -v /var/swapfile | awk '$1=="0:" {print substr($4, 1, length($4)-2)}'
    "resume_offset=13224121"
  ];

  boot.kernel.sysctl = {

    #"net.ipv4.tcp_syncookies" = false; # example

    # https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate
    # Tip: You might want to decrease the swappiness for your swap file
    # if the only purpose is to be able to hibernate and not expand RAM.
    # https://wiki.archlinux.org/title/Swap#Swappiness
    "vm.swappiness" = 10;

  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  #hardware.video.hidpi.enable = lib.mkDefault true;
  # TODO hidpi
  #fonts.fontconfig = TODO;
}
